schema_version = "1.0.0"

id = "io_artiste"
version = "2.0.0"
name = "SuperTuxKart Runner"
tagline = "Nodal Editor SuperTuxKart Project"
maintainer = "LLS"
type = "add-on"

tags = ["Node"]

blender_version_min = "2.80.0"
# blender_version_max = "5.1.0"

license = [
  "SPDX:MIT",
]
copyright = [
   "2009-2020 SuperTuxKart-Team",
]
